version: "3.5"
services:

  sui:
    container_name: sui
    restart: always
    build:
      context: ./
    environment:
      - VIRTUAL_HOST=test.laserr.net
    ports:
      - 8282:80
    volumes:
      - ./:/usr/share/nginx/html

